language: ruby
rvm:
 - 2.3.3
 - 2.2
node_js: 6
before_install:
    - bash ./scripts/nvm.sh
    - npm install
script:
    - ./scripts/cibuild
after_success:
    - surge --project ./_site --domain $STAGING_SURGE


